image: nextmetaphor/yaml-graph:latest
variables:
  GIT_SUBMODULE_STRATEGY: recursive
pages:
  stage: deploy
  script:
    - pwd
    - ls -la
    - find .
    - yaml-graph validate -s cloud-taxonomy/taxonomy -s blueprints -f taxonomy/definition-format.yml
    - yaml-graph load -s cloud-taxonomy/taxonomy -s blueprints
    - yaml-graph report --fields report/by-blueprint-category/fields.yaml --template report/by-blueprint-category/template.gohtml > report/by-blueprint-category/by-blueprint-category.html
    - cp report/by-blueprint-category/by-blueprint-category.html public/index.html
  artifacts:
    paths:
      - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
