image: nextmetaphor/yaml-graph:latest
variables:
  GIT_SUBMODULE_STRATEGY: recursive
pages:
  stage: deploy
  script:
    - sleep 20
    - yaml-graph validate -s cloud-taxonomy/definition -s cloud-architecture-framework/definition -s definition -f cloud-taxonomy/definition/definition-format.yml -f cloud-architecture-framework/definition/definition-format.yml -f definition/definition-format.yml
    - yaml-graph load -s cloud-taxonomy/definition -s cloud-architecture-framework/definition -s definition
    - yaml-graph report --fields report/by-blueprint-category/fields.yaml --template report/by-blueprint-category/template.gohtml > report/by-blueprint-category/by-blueprint-category.html
    - cp report/by-blueprint-category/by-blueprint-category.html public/index.html
    - yaml-graph report --fields report/BlueprintByCategoryJSON/fields.yaml --template report/BlueprintByCategoryJSON/template.gohtml > report/BlueprintByCategoryJSON/document.json
    - cp report/BlueprintByCategoryJSON/document.json public/BlueprintByCategoryJSON.json
    - yaml-graph report --fields report/BlueprintByFrameworkJSON/fields.yaml --template report/BlueprintByFrameworkJSON/template.gohtml > report/BlueprintByFrameworkJSON/document.json
    - cp report/BlueprintByFrameworkJSON/document.json public/BlueprintByFrameworkJSON.json

  artifacts:
    paths:
      - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
